### ISSUE TITLE
About an example test code of popsan_ddpg on GPU

### ISSUE THREAD

**Issue by xdliu91** [combra-lab/pop-spiking-deep-rl#3]
import numpy as np
import torch
import torch.nn as nn
import gym
import pickle
import sys
import math

sys.path.append('../../')
from popsan_drl.popsan_td3.replay_buffer_norm import ReplayBuffer
from popsan_drl.popsan_td3.popsan import PopSpikeActor

with torch.no_grad():

    def test_best_models(env_name, model_num, result_dir, spike_ts=5, encoder_pop_dim=10, decoder_pop_dim=10,
                         std=math.sqrt(0.15), max_ep_len=1000):
        # Initialize test environment
        env = gym.make(env_name)
        obs_dim = env.observation_space.shape[0]
        act_dim = env.action_space.shape[0]
        act_limit = env.action_space.high[0]

        for m in range(model_num):
            test_reward, _ = pickle.load(open(result_dir + '/model' + str(m) + '_test_rewards.p', 'rb'))
            best_epoch_idx = 5
            best_epoch_reward = 0
            for idx in range(20):
                if test_reward[(idx + 1) * 5 - 1] < best_epoch_reward:
                    best_epoch_reward = test_reward[(idx + 1) * 5 - 1]
                    best_epoch_idx = (idx + 1) * 5
            print("Train Model: ", m, " Best Epoch: ", best_epoch_idx, " Reward: ", best_epoch_reward)
            model_dir = result_dir + '/model' + str(m) + '_e' + str(best_epoch_idx) + '.pt'
            buffer_dir = result_dir + '/model' + str(m) + '_e' + str(best_epoch_idx) + '_mean_var.p'

        # Set device
        device = torch.device("cpu")

        # Load the saved model and saved input normalization mean and var

        # Replay buffer for running z-score norm
        b_mean_var = pickle.load(open(buffer_dir, "rb"))
        replay_buffer = ReplayBuffer(obs_dim=obs_dim, act_dim=act_dim, size=1,
                                     clip_limit=3, norm_update_every=1)
        replay_buffer.mean = b_mean_var[0]
        replay_buffer.var = b_mean_var[1]
        # PopSAN
        popsan = PopSpikeActor(obs_dim, act_dim, encoder_pop_dim, decoder_pop_dim, (256, 256),
                               (-3, 3), std, spike_ts, act_limit, device, False)
        popsan.load_state_dict(torch.load(model_dir))
        print(model_dir)

        # test_agent
        def get_action(o):
            a = popsan(torch.as_tensor(o, dtype=torch.float32, device=device), 1).to('cpu').numpy()
            # print(a)
            return np.clip(a, -act_limit, act_limit)

        test_reward_sum = 0
        o, d, ep_ret, ep_len = env.reset(), False, 0, 0
        while not (d or (ep_len == max_ep_len)):
            # print(ep_len)
            env.render()
            # Take deterministic actions at test time (noise_scale=0)
            o, r, d, _ = env.step(get_action(replay_buffer.normalize_obs(o)))
            ep_ret += r
            ep_len += 1
            # if d:
            #     o = env.reset()
            test_reward_sum += ep_ret

    if __name__ == '__main__':
        data_dir = 'E:\pop-spiking-deep-rl-main\popsan_drl\popsan_td3\params\spike-td3_td3-popsan-HalfCheetah-v3-encoder-dim-10-decoder-dim-10'
        env_name = "HalfCheetah-v3"
        model_num = 10
        r_list, i_list, in_mem = test_best_models(env_name, model_num, data_dir)

**Comment by michaelgzt** [comment]
Hi Xiaode, I cannot find any obvious problem in the code. Can you tell us what went wrong when running the code?

**Comment by michaelgzt** [comment]
I had a more detailed look at your code. Here's a possible bug you may have in the code:

When you create PopSAN object you should initialize the object using:

`popsan = PopSpikeActor(obs_dim, act_dim, encoder_pop_dim, decoder_pop_dim, (256, 256), (-3, 3), std, spike_ts, act_limit, device, False)`

You can see the definition of `PopSpikeActor` here:

https://github.com/combra-lab/pop-spiking-deep-rl/blob/5fe5f39eeb859af978bfc52a796e7b8a5ff7517e/popsan_drl/popsan_td3/popsan.py#L228

**Comment by xdliu91** [comment]
Hi guangzi,
Thanks for your prompt reply.
The problem lies at the test_agent function. 
the problem is about this line **"a = ac.act(torch.as_tensor(o, dtype=torch.float32, device=device), 1)"** with the error **'ac' is not defined.**
Althgouth I try to initialize the object using **from ddpg_cuda_norm import SpikeActorDeepCritic** with adding the statement in the function def test_best_models, another error occured, which is **TypeError: act() missing 1 required positional argument: 'batch_size'**.
Could you please help me find where the problem is? 
Thanks very much for your time.

**Comment by michaelgzt** [comment]
Suppose you trained the model using PopSAN + TD3.

The `ac` object is defined using the `SpikeActorDeepCritic` class which is a wrapper of the actor and critic networks. The class is defined in:

https://github.com/combra-lab/pop-spiking-deep-rl/blob/5fe5f39eeb859af978bfc52a796e7b8a5ff7517e/popsan_drl/popsan_td3/td3_cuda_norm.py#L19

However, the model is saved as a `PopSpikeActor` object. In your code, you reload the saved model using:

`popsan.load_state_dict(torch.load(model_dir))`

As a result, you **cannot** use the `ac` to generate the action, since the object is not defined. You need to change line:

`a = ac.act(torch.as_tensor(o, dtype=torch.float32, device=device), 1)`

Into a line directly generating action using `popsan`:

`a = popsan(o, 1).to('cpu').numpy()`

Also, remember to wrap everything in `with torch.no_grad():`.

**Comment by xdliu91** [comment]
Thanks for your nice reply.
I'm sorry I didn't reply you in time due to my personal reason.
After using the line
**a = popsan(o, 1).to('cpu').numpy()**
another error occurs, which is **TypeError: view() takes at most 2 arguments (3 given)**, and the error pointed at the "popsan_td3\popsan.py", line 71,
https://github.com/combra-lab/pop-spiking-deep-rl/blob/5fe5f39eeb859af978bfc52a796e7b8a5ff7517e/popsan_drl/popsan_td3/popsan.py#L71

Thanks again for your time.
Best wishes.

**Comment by michaelgzt** [comment]
This may be because you directly use a Numpy array as input to the forward function of PopSAN.

You can change this link in your `get_action` function from:

`a = popsan(o, 1).to('cpu').numpy()`

to:

`a = popsan(torch.as_tensor(o, dtype=torch.float32, device=device), 1).to('cpu').numpy()`

**Comment by xdliu91** [comment]
Thanks for your useful reply.
Fllowing your advice, the code has been sucessfully run.
However, the action in gym env is static，which the error is **TypeError: 'NoneType' object is not iterable**
Thanks for your kindly help.

**Comment by michaelgzt** [comment]
For this problem, you need to check the correctness of your trained model. This can happen if the model is not properly trained. I recommend you to train the model using TD3, which has a better performance than DDPG, and select the best model during training for inference.

**Comment by michaelgzt** [comment]
Can you try to delete this line from your test loop:

`
if d: o = env.reset()
`

It's possible when `d==True` all the time, your code is resetting the environment every step.

**Comment by xdliu91** [comment]
Thanks for your advice.
I had tried this before but it had no effect on the model.
I have carefully checked the test code and update it again.
Thanks again for your time!
