### ISSUE TITLE
loihi_realization test_lohi.py

### ISSUE THREAD

**Issue by lucifer2859** [combra-lab/pop-spiking-deep-rl#4]
![image](https://user-images.githubusercontent.com/26899067/182851381-98c008db-7593-4461-b84e-77063ab4dfdf.png)

WARNING:DRV:  elementType would be deprecated in 0.9 in favor of messageSize, which provides more flexibility
WARNING:DRV:  elementType would be deprecated in 0.9 in favor of messageSize, which provides more flexibility
INFO:DRV:  SLURM is being run in background
INFO:HST:  srun: error: Unable to allocate resources: Invalid node name specified
WARNING:DRV:  Connection is taking longer than usual.
WARNING:DRV:  Boards might be busy or consider reasons below:
WARNING:DRV:  1. If you are working on INRC Cloud, ensure setting SLURM=1.
WARNING:DRV:  2. Run sinfo to check if all boards are down.
WARNING:DRV:  3. Check squeue below for any unfinished jobs. Run scancel <JOBID> to cancel hung jobs.
WARNING:DRV:  JOBID     NAME                          PARTITION TIME      NODELIST(REASON)    USER

Do you know how to ensure the first two items?

**Comment by lucifer2859** [comment]
error: PHDR segment not covered by LOAD segment

board.createSnip Error

**Comment by michaelgzt** [comment]
Hi, this question is related to the Loihi hardware and environment you are using, please contact nrc_support@intel-research.net for general questions about running code on Loihi.
